// Decompiled with JetBrains decompiler
// Type: Game.Prefabs.NetPieceRequirements
// Assembly: Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 6E65E546-90EB-41EE-A5F5-E22CC56BB1AC
// Assembly location: C:\Program Files (x86)\Steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Game.dll

using Game.UI.Editor;

#nullable disable
namespace Game.Prefabs
{
  public enum NetPieceRequirements
  {
    [HideInEditor] Node,
    [HideInEditor] Intersection,
    [HideInEditor] DeadEnd,
    [HideInEditor] Crosswalk,
    [HideInEditor] BusStop,
    [HideInEditor] Median,
    [HideInEditor] TrainStop,
    [HideInEditor] OppositeTrainStop,
    [HideInEditor] Inverted,
    [HideInEditor] TaxiStand,
    [HideInEditor] LevelCrossing,
    Elevated,
    [HideInEditor] Tunnel,
    [HideInEditor] Raised,
    [HideInEditor] Lowered,
    [HideInEditor] LowTransition,
    [HideInEditor] HighTransition,
    [HideInEditor] WideMedian,
    [HideInEditor] TramTrack,
    [HideInEditor] TramStop,
    [HideInEditor] OppositeTramTrack,
    [HideInEditor] OppositeTramStop,
    [HideInEditor] MedianBreak,
    [HideInEditor] ShipStop,
    [HideInEditor] Sidewalk,
    [HideInEditor] Edge,
    [HideInEditor] SubwayStop,
    [HideInEditor] OppositeSubwayStop,
    [HideInEditor] MiddlePlatform,
    [HideInEditor] Underground,
    [HideInEditor] Roundabout,
    [HideInEditor] OppositeSidewalk,
    [HideInEditor] SoundBarrier,
    [HideInEditor] Overhead,
    [HideInEditor] TrafficLights,
    [HideInEditor] PublicTransportLane,
    [HideInEditor] OppositePublicTransportLane,
    [HideInEditor] Spillway,
    [HideInEditor] MiddleGrass,
    [HideInEditor] MiddleTrees,
    [HideInEditor] WideSidewalk,
    [HideInEditor] SideGrass,
    [HideInEditor] SideTrees,
    [HideInEditor] OppositeGrass,
    [HideInEditor] OppositeTrees,
    [HideInEditor] Opening,
    [HideInEditor] Front,
    [HideInEditor] Back,
    [HideInEditor] Flipped,
    RemoveTrafficLights,
    [HideInEditor] AllWayStop,
    [HideInEditor] Pavement,
    [HideInEditor] Gravel,
    [HideInEditor] Tiles,
    ForbidLeftTurn,
    ForbidRightTurn,
    [HideInEditor] OppositeWideSidewalk,
    OppositeForbidLeftTurn,
    OppositeForbidRightTurn,
    [HideInEditor] OppositeSoundBarrier,
    [HideInEditor] SidePlatform,
    [HideInEditor] AddCrosswalk,
    RemoveCrosswalk,
    [HideInEditor] Lighting,
    [HideInEditor] OppositeBusStop,
    [HideInEditor] OppositeTaxiStand,
    [HideInEditor] OppositeRaised,
    [HideInEditor] OppositeLowered,
    [HideInEditor] OppositeLowTransition,
    [HideInEditor] OppositeHighTransition,
    [HideInEditor] OppositeShipStop,
    [HideInEditor] OppositePlatform,
    [HideInEditor] OppositeAddCrosswalk,
    [HideInEditor] OppositeRemoveCrosswalk,
    [HideInEditor] Inside,
    ForbidStraight,
    OppositeForbidStraight,
    [HideInEditor] Hidden,
    [HideInEditor] ParkingSpaces,
    [HideInEditor] OppositeParkingSpaces,
  }
}
